# Generated by Django 5.2.13 on 2026-05-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_address_customerprofile_notification_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, help_text='e.g. Rectangle, Round, Runner', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='space',
            field=models.CharField(blank=True, help_text='e.g. Living Room, Bedroom, Office', max_length=100, null=True),
        ),
    ]
